-- AlterTable
ALTER TABLE "FixedAsset" ADD COLUMN     "landValue" DECIMAL(20,4) NOT NULL DEFAULT 0,
ADD COLUMN     "ratePct" DECIMAL(6,3) NOT NULL DEFAULT 0,
ADD COLUMN     "regime" TEXT NOT NULL DEFAULT 'US';
