// Gera o pacote de subscrição PREENCHIDO (Subscription Agreement + Amendment & Joinder)
// a partir das respostas do wizard — versão EXECUTION: sem NOTE/QUESTIONS de advogado
// (esses vivem só no template DRAFT em revisão). Fonte do template: sub-generate.js /
// oa-generate.js (Exhibit B), congelados em 19/07/2026 aguardando o advogado.
import {
  AlignmentType,
  Document,
  Footer,
  Header,
  HeadingLevel,
  Packer,
  PageNumber,
  Paragraph,
  TextRun,
} from "docx";
import { ACCREDITATION_OPTIONS, type WizardData } from "@/lib/subscription/types";

const FONT = "Times New Roman";
const SZ = 22;
const t = (text: string, opts: Record<string, unknown> = {}) =>
  new TextRun({ text, font: FONT, size: SZ, ...opts });

const H1 = (n: string, text: string) =>
  new Paragraph({
    heading: HeadingLevel.HEADING_1,
    spacing: { before: 320, after: 160 },
    children: [t(`PART ${n} — ${text}`, { bold: true, size: 24 })],
  });

const P = (label: string | null, text: string | TextRun[], opts: Record<string, unknown> = {}) =>
  new Paragraph({
    spacing: { after: 120 },
    alignment: AlignmentType.JUSTIFIED,
    children: [...(label ? [t(`${label} `, { bold: true })] : []), ...(Array.isArray(text) ? text : [t(text)])],
    ...opts,
  });

const LI = (text: string) =>
  new Paragraph({
    spacing: { after: 60 },
    alignment: AlignmentType.JUSTIFIED,
    indent: { left: 720 },
    children: [t(text)],
  });

const CENTER = (text: string, opts: Record<string, unknown> = {}) =>
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 120 }, children: [t(text, opts)] });

export type SubscriptionDocInput = {
  poolName: string; // razão social da LLC (ex.: "Vixus Home Partners I LLC")
  poolCode: string;
  managerName: string; // entidade gestora
  county: string;
  unitPrice: number;
  data: WizardData;
  signName?: string | null;
  signedAt?: Date | null;
  signIp?: string | null;
  signHash?: string | null;
};

const money = (n: number) =>
  "US$" + n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

const blank = (s: string | undefined | null, fallback = "________________") =>
  s && s.trim() ? s.trim() : fallback;

function pageShell(footerLeft: string, children: Paragraph[]) {
  return new Document({
    styles: { default: { document: { run: { font: FONT, size: SZ } } } },
    sections: [
      {
        properties: {
          page: {
            size: { width: 12240, height: 15840 },
            margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 },
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  t("GENERATED BY THE VIXUS PLATFORM — SUBJECT TO MANAGER ACCEPTANCE", {
                    bold: true,
                    color: "666666",
                    size: 16,
                  }),
                ],
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  t(`${footerLeft}  ·  Page `, { size: 16, color: "666666" }),
                  new TextRun({ children: [PageNumber.CURRENT], font: FONT, size: 16, color: "666666" }),
                ],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });
}

function signatureBlock(input: SubscriptionDocInput): Paragraph[] {
  const d = input.data;
  const isIndividual = d.type === "INDIVIDUAL";
  const signed = input.signName && input.signedAt;
  const sigLine = signed
    ? `/s/ ${input.signName} — signed electronically on ${input.signedAt!.toISOString().slice(0, 10)}`
    : "_________________________________    Date: _______________";
  const audit = signed
    ? [
        P(null, [
          t(
            `Electronic signature record: name typed "${input.signName}" · IP ${blank(input.signIp, "n/a")} · SHA-256 ${blank(
              input.signHash,
              "n/a",
            )}. The Investor consented to electronic execution (E-SIGN/UETA).`,
            { size: 16, color: "666666" },
          ),
        ]),
      ]
    : [];
  return [
    new Paragraph({
      spacing: { before: 400, after: 200 },
      children: [t("IN WITNESS WHEREOF, the Investor has executed this Subscription Agreement as of the date stated below.")],
    }),
    P(null, [t(isIndividual ? "INVESTOR (individual):" : "INVESTOR (entity or trust):", { bold: true })]),
    ...(isIndividual ? [] : [P(null, blank(d.legalName))]),
    P(null, `By: ${sigLine}`),
    P(null, `Name: ${blank(input.signName ?? d.legalName)}${isIndividual ? "" : " · Title: authorized signatory"}`),
    ...audit,
    P(null, [
      t("The Investor is simultaneously executing the Amendment and Joinder in the form of Exhibit B to the Operating Agreement.", {
        italics: true,
        size: 20,
      }),
    ]),
    new Paragraph({ spacing: { before: 300, after: 120 }, children: [t("ACCEPTANCE", { bold: true })] }),
    P(null, [
      t(
        `Accepted as of _______________, for ${d.units ?? "____"} Units and a Capital Commitment of ${
          d.units ? money(d.units * input.unitPrice) : "____"
        }.`,
      ),
    ]),
    P(null, `${input.poolName}`),
    P(null, `By: ${input.managerName}, its Manager`),
    P(null, "By: _________________________________    Date: _______________"),
  ];
}

export async function buildSubscriptionDocx(input: SubscriptionDocInput): Promise<Buffer> {
  const d = input.data;
  const commitment = d.units ? money(d.units * input.unitPrice) : "____";
  const accreditation = (d.accreditation ?? [])
    .map((k) => ACCREDITATION_OPTIONS.find((o) => o.key === k)?.en)
    .filter(Boolean) as string[];
  const ubo = (d.ubo ?? []).filter((r) => r.name?.trim());

  const doc = pageShell(`Subscription Agreement — ${input.poolName}`, [
    CENTER("SUBSCRIPTION AGREEMENT", { bold: true, size: 32 }),
    CENTER("AND INVESTOR QUESTIONNAIRE", { bold: true, size: 26 }),
    CENTER("for the purchase of Units of", { size: 22 }),
    CENTER(input.poolName, { bold: true, size: 30 }),
    CENTER("a Florida limited liability company", { italics: true }),
    CENTER(""),
    P(null, [
      t("This Subscription Agreement (this "),
      t("“Agreement”", { bold: true }),
      t(") is entered into between "),
      t(blank(d.legalName), { bold: true }),
      t(" (the "),
      t("“Investor”", { bold: true }),
      t(") and "),
      t(input.poolName, { bold: true }),
      t(" (the "),
      t("“Company”", { bold: true }),
      t("), acting through its manager, "),
      t(input.managerName, { bold: true }),
      t(" (the "),
      t("“Manager”", { bold: true }),
      t("). Capitalized terms used and not defined in this Agreement have the meanings given to them in the Operating Agreement of the Company, as amended from time to time (the "),
      t("“Operating Agreement”", { bold: true }),
      t("). The offering of Units is made only pursuant to the Offering Documents and in reliance on Rule 506(b) of Regulation D."),
    ]),

    H1("I", "SUBSCRIPTION"),
    P(
      "1.1 Subscription; Capital Commitment.",
      `The Investor irrevocably subscribes for ${d.units ?? "____"} Units of the Company at a price of ${money(
        input.unitPrice,
      )} per Unit, for a total capital commitment of ${commitment} (the “Capital Commitment”), subject to acceptance by the Manager under Section 1.4. The Units are governed by the Operating Agreement, which the Investor has received and reviewed.`,
    ),
    P(
      "1.2 Funding; Capital Calls.",
      "The Investor shall fund the Capital Commitment in installments pursuant to capital calls issued by the Manager under Article IV of the Operating Agreement, upon at least ten (10) business days' prior written notice. The Investor acknowledges that failure to fund a capital call when due is subject to the default provisions and remedies of Section 4.4 of the Operating Agreement, including dilution, subordination and forced-sale remedies described therein.",
    ),
    P(
      "1.3 Payment; Wire Security.",
      "All payments shall be made only by wire transfer in accordance with written wire instructions delivered by the Manager through the Company's investor portal or another verified channel. The Company will never change wire instructions by e-mail alone. Before the first transfer, and before acting on any change of instructions, the Investor must verify the instructions by telephone with a known representative of the Manager using contact information obtained independently of the message conveying the instructions.",
    ),
    P(
      "1.4 Acceptance; Rejection.",
      "This subscription is subject to acceptance by the Manager, in whole or in part, in its sole discretion. The subscription shall be effective only when the Manager countersigns this Agreement, and admission of the Investor as a Member shall be effective when the Manager executes the Amendment and Joinder and amends and restates Exhibit A of the Operating Agreement pursuant to Sections 3.3 and 11.2(a) thereof. If this subscription is rejected in whole or in part, the corresponding funds received will be returned promptly, without interest or deduction.",
    ),
    P(
      "1.5 Joinder to the Operating Agreement.",
      "Simultaneously with this Agreement, the Investor is executing an Amendment and Joinder in the form of Exhibit B to the Operating Agreement. Upon acceptance, the Investor shall be admitted as a Member, shall be a party to and bound by all terms of the Operating Agreement, and shall be listed on Exhibit A thereof with the Units and Capital Commitment stated in this Agreement.",
    ),
    P(
      "1.6 Irrevocability.",
      "This subscription is irrevocable on the part of the Investor, and shall terminate only if the Manager rejects it under Section 1.4 or the offering is terminated by the Manager.",
    ),

    H1("II", "REPRESENTATIONS AND WARRANTIES OF THE INVESTOR"),
    P(
      "2.1 Authority.",
      "The Investor has full power and authority to execute and perform this Agreement and the Amendment and Joinder. If the Investor is an entity or trust, it is duly organized or formed, validly existing and in good standing in its jurisdiction, the execution of this Agreement has been duly authorized, and the individual signing on its behalf is duly empowered to do so.",
    ),
    P(
      "2.2 Securities Matters.",
      "The Investor represents that: (a) the Units have not been registered under the Securities Act of 1933 or any state securities laws, and are being acquired for the Investor's own account, for investment purposes only and not with a view to distribution or resale; (b) the Investor meets the applicable suitability requirements described in the Offering Documents and has such knowledge and experience in financial and business matters as to evaluate the merits and risks of this investment; (c) no Units were offered to the Investor by any form of general solicitation or advertising (Rule 506(b)); (d) the Units are restricted securities that may not be transferred except in compliance with Article VII of the Operating Agreement and applicable securities laws, the Investor may be required to hold the Units indefinitely, and no public or private market for the Units exists or is expected to develop; and (e) the Investor can bear the economic risk of a complete loss of its investment.",
    ),
    P(
      "2.3 Access to Information; No Reliance on Projections.",
      "The Investor has received and reviewed the Offering Documents, including the Operating Agreement and the risk factors described therein; has had the opportunity to ask questions of, and receive answers from, the Manager; and has relied solely on the Offering Documents and the advice of the Investor's own advisers. Any financial projection, target return, timeline or estimate is inherently uncertain, is not a guarantee of performance, and actual results may differ materially.",
    ),
    P(
      "2.4 Risk Acknowledgment.",
      "The Investor acknowledges the risks described in the Offering Documents, including real estate development and construction risks, market and interest-rate risks, financing risks, the illiquidity and finite-life nature of the Company, and the possibility of losing the entire investment. Distributions are not assured, depend on Distributable Cash as defined in the Operating Agreement, and are subject to the priorities of the waterfall in Section 5.2 thereof.",
    ),
    P(
      "2.5 Anti-Money Laundering; Sanctions; Source of Funds.",
      "The Investor represents that it is not, and is not owned or controlled by, a person listed on any sanctions list administered by OFAC or any equivalent authority; that the funds used for this investment are from lawful sources; and that it will promptly provide any information reasonably requested to enable the Company and its financial institutions to comply with anti-money-laundering, know-your-customer and sanctions obligations.",
    ),
    P(
      "2.6 Tax Matters.",
      "The Investor has consulted, or has had the opportunity to consult, its own tax advisers regarding the tax consequences of the investment, including, for non-U.S. investors, the consequences in the Investor's home jurisdiction. The Investor acknowledges that allocations, distributions and transfers may be subject to U.S. tax withholding, reporting and filing requirements administered by the Company as described in the Operating Agreement, and agrees to deliver and keep current the tax documentation applicable to its status.",
    ),
    P(
      "2.7 Electronic Delivery; Electronic Signature.",
      "The Investor consents to the electronic delivery of all reports, statements, tax documents (including Schedule K-1), notices and other communications through the Company's investor portal or to the e-mail address stated in Part III, and agrees that electronic signatures shall have the same effect as original signatures.",
    ),
    P(
      "2.8 Accuracy; Updates; Indemnity.",
      "The representations in this Agreement and the information in the Investor Questionnaire are true and complete as of the date of this Agreement and will be true and complete as of acceptance; the Investor will promptly notify the Manager of any material change. The Investor shall indemnify and hold harmless the Company and the Manager from any loss, cost or liability (including reasonable attorneys' fees) arising out of any material misrepresentation by the Investor in this Agreement or the Investor Questionnaire.",
    ),

    H1("III", "INVESTOR QUESTIONNAIRE"),
    P("3.1 Identity.", ""),
    LI(`Legal name of Investor: ${blank(d.legalName)}`),
    LI(`Type: ${blank(d.type)}`),
    LI(`Jurisdiction of residence or organization: ${blank(d.jurisdiction)}`),
    LI(`Taxpayer identification number: ${blank(d.tin)}`),
    LI(`Principal address: ${blank(d.address)}`),
    LI(`E-mail for notices and portal access: ${blank(d.email)} · Phone: ${blank(d.phone, "—")}`),
    P("3.2 Accredited Investor Status.", accreditation.length ? "The Investor certifies that it qualifies as an “accredited investor” under Regulation D on the following basis:" : "________________"),
    ...accreditation.map((a) => LI(`☑ ${a}`)),
    P(
      "3.3 Beneficial Ownership.",
      ubo.length
        ? "Individuals owning 25% or more of the Investor, and control person:"
        : "Not applicable (individual investor) or to be provided upon request.",
    ),
    ...ubo.map((r) => LI(`• ${r.name} — ${blank(r.pct, "—")}${r.control ? " · control person" : ""}`)),
    P(
      "3.4 U.S. Tax Status.",
      d.usPerson === undefined
        ? "________________"
        : d.usPerson
          ? `The Investor is a “United States person” (IRS Form W-9 to be delivered).${d.taxClassification ? ` Entity U.S. tax classification: ${d.taxClassification}.` : ""}`
          : `The Investor is not a “United States person” (applicable IRS Form W-8 series to be delivered).${d.taxClassification ? ` Entity U.S. tax classification: ${d.taxClassification}.` : ""}`,
    ),
    P("3.5 Source of Funds.", blank(d.sourceOfFunds)),

    H1("IV", "GENERAL PROVISIONS"),
    P(
      "4.1 Governing Law; Disputes.",
      `This Agreement is governed by the laws of the State of Florida, without regard to conflicts of law. Any dispute arising out of or relating to this Agreement shall be resolved in the same manner, in the same forum and subject to the same jury waiver as provided in Section 11.4 of the Operating Agreement (mediation followed by binding arbitration administered by the American Arbitration Association, seated in ${input.county} County, Florida), which is incorporated by reference.`,
    ),
    P(
      "4.2 Relationship to the Operating Agreement.",
      "This Agreement governs the subscription for and admission to the Company; the Operating Agreement governs the governance, economics, distributions and transfers of the Company. In the event of a conflict after admission, the Operating Agreement controls.",
    ),
    P("4.3 Survival.", "The representations, warranties and indemnity of the Investor survive the acceptance of this subscription and the admission of the Investor as a Member."),
    P(
      "4.4 Counterparts; Electronic Signatures.",
      "This Agreement may be executed in counterparts and by electronic signature, each of which is an original and all of which together are one instrument.",
    ),
    ...signatureBlock(input),
  ]);

  return Packer.toBuffer(doc) as Promise<Buffer>;
}

export async function buildJoinderDocx(input: SubscriptionDocInput): Promise<Buffer> {
  const d = input.data;
  const signed = input.signName && input.signedAt;
  const sigLine = signed
    ? `/s/ ${input.signName} — signed electronically on ${input.signedAt!.toISOString().slice(0, 10)}`
    : "_________________________________    Date: _______________";

  const doc = pageShell(`Amendment & Joinder — ${input.poolName}`, [
    CENTER("AMENDMENT AND JOINDER", { bold: true, size: 30 }),
    CENTER("to the Operating Agreement — Admission of Additional Member", { bold: true }),
    CENTER(""),
    P(null, [
      t(`AMENDMENT No. ___ TO THE OPERATING AGREEMENT OF ${input.poolName.toUpperCase()}. `, { bold: true }),
      t(
        "Pursuant to Sections 3.3, 3.4 and 11.2(a) of the Operating Agreement, the Manager hereby (a) admits the undersigned subscriber (the “New Member”) as a Member of the Company, effective upon the Manager's acceptance below; and (b) amends and restates Exhibit A in the form attached hereto to reflect such admission and the corresponding Units and Capital Contribution.",
      ),
    ]),
    P(
      "Joinder of New Member.",
      "The undersigned New Member, in consideration of its admission to the Company, hereby (i) joins and agrees to be bound by all terms and conditions of the Operating Agreement as a Member; (ii) confirms its subscription agreement and the Capital Contribution set forth on the restated Exhibit A; (iii) delivers the applicable IRS Form W-9 or W-8 series form; and (iv) acknowledges the tax provisions of Article VI of the Operating Agreement.",
    ),
    P(null, [t("NEW MEMBER:", { bold: true })]),
    P(null, blank(d.legalName)),
    P(null, `By: ${sigLine}`),
    ...(signed
      ? [
          P(null, [
            t(
              `Electronic signature record: name typed "${input.signName}" · IP ${blank(input.signIp, "n/a")} · SHA-256 ${blank(
                input.signHash,
                "n/a",
              )}.`,
              { size: 16, color: "666666" },
            ),
          ]),
        ]
      : []),
    P(null, [t("ACCEPTED — MANAGER (sole signature required to effect the admission and restate Exhibit A):", { bold: true })]),
    P(null, input.managerName),
    P(null, "By: _________________________________    Date: _______________"),
    P(null, ""),
    P(null, [
      t("Attachment: ", { bold: true }),
      t("Exhibit A, as amended and restated as of the date of this Amendment (generated from the Company's capital ledger)."),
    ]),
  ]);

  return Packer.toBuffer(doc) as Promise<Buffer>;
}
