ALTER TABLE "PoolLoan" ADD COLUMN IF NOT EXISTS "interestDueDay" INTEGER;
ALTER TABLE "PoolLoan" ADD COLUMN IF NOT EXISTS "graceDays" INTEGER;
ALTER TABLE "PoolLoan" ADD COLUMN IF NOT EXISTS "lateFeePct" DECIMAL(6,3);
